Task: RLHF
Model: models/SFT/gpt2
Dataset: imdb
Seed: 42
OutputDir: output/Run2


DataConfig: 
  only_positive: False
  eval_size: 2500
  test_size: 5000


PromptConfig:
  min_tokens: 2
  max_tokens: 8

PPOConfig:
  learning_rate: 1.0e-05
  vf_coef: 0.5
  batch_size: 112
  mini_batch_size: 28
  ppo_epochs: 5
  use_score_scaling: True
  use_score_norm: True


GenerationConfig:
  do_sample: True
  top_k: 0.0
  min_length: -1
  max_new_tokens: 32
  top_p: 1.0


RewardConfig:
  RewardModel: models/Default/distilbert
  label_idx: 1


MetricConfig:
  RewardModel: models/Default/distilbert
  label_idx: 1