Task: DPO
Model: models/SFT/gpt2
Dataset: imdb
Seed: 42
OutputDir: output/Run12
DatasetDir: datasets


DataConfig: 
  only_positive: False
  eval_size: 2500
  test_size: 5000


PromptConfig:
  min_tokens: 2
  max_tokens: 8


DPOConfig:
  beta: 0.5
  learning_rate: 1.0e-05
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16  
  logging_steps: 10
  save_steps: 500
  eval_steps: 100


GenerationConfig:
  do_sample: True
  top_k: 0.0
  min_length: -1
  max_new_tokens: 32
  top_p: 1.0


RewardConfig:
  RewardModel: models/Default/distilbert
  label_idx: 1


MetricConfig:
  RewardModel: models/Default/distilbert
  label_idx: 1